name = "NonLinearProg"
uuid = "59a653e0-4fd1-4c37-892e-cada1571c056"
authors = ["pauline.corblet <pauline.corblet@sciencespo.fr>"]
version = "0.1.0"

[deps]
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
